#ifndef BOARD_PINS_H
#define BOARD_PINS_H

#include "stc8h_sfr.h"

#define BOARD_LAMP_PWM_PORT 1u
#define BOARD_LAMP_PWM_PIN 0u
#define BOARD_LAMP_PWM_MASK 0x01u

#define BOARD_STATUS_LED_PORT 1u
#define BOARD_STATUS_LED_PIN 1u
#define BOARD_STATUS_LED_MASK 0x02u

#define BOARD_P1_USED_MASK (BOARD_LAMP_PWM_MASK | BOARD_STATUS_LED_MASK)
#define BOARD_P1_UNUSED_MASK ((stc8h_u8)~BOARD_P1_USED_MASK)

#define BOARD_UART1_RX_PIN 0u
#define BOARD_UART1_TX_PIN 1u
#define BOARD_UART1_RX_MASK 0x01u
#define BOARD_UART1_TX_MASK 0x02u
#define BOARD_UART1_MASK (BOARD_UART1_RX_MASK | BOARD_UART1_TX_MASK)

#define BOARD_IR_RX_PORT 3u
#define BOARD_IR_RX_PIN 2u
#define BOARD_IR_RX_MASK 0x04u
#define BOARD_P3_ACTIVE_USED_MASK (BOARD_IR_RX_MASK | BOARD_UART1_MASK)
#define BOARD_P3_ACTIVE_UNUSED_MASK ((stc8h_u8)~BOARD_P3_ACTIVE_USED_MASK)
#define BOARD_P3_POWER_USED_MASK BOARD_IR_RX_MASK
#define BOARD_P3_POWER_UNUSED_MASK ((stc8h_u8)~BOARD_P3_POWER_USED_MASK)

#define BOARD_IR_RX_READ() (((P3 & BOARD_IR_RX_MASK) != 0u) ? 1u : 0u)

#endif
