[platformio]
default_envs = STC8H1K08

[env:STC8H1K08]
platform = intel_mcs51
board = STC8H1K08
board_build.f_cpu = 6000000L
extra_scripts = post:upload_stcgal.py
custom_stcgal_protocol = stc8g
custom_stcgal_trim = 6000
custom_stcgal_baud = 38400
build_flags =
    -Iinclude
    -Iboard/stc8h1k08_ir_lamp_remote
    -I../../../../foundation/Stc8hBase/core
    -I../../../../foundation/Stc8hBase/hal
    -I../../../../foundation/Stc8hBase/drivers
    -I../../../../foundation/Stc8hBase/utils
    -DSTC8H_TIMER0_ROLE_1T_DELAY
    -DAPP_IR_ACTIVE_LEVEL=1
    -DAPP_LED_FEEDBACK_ENABLE=1

[env:STC8H1K08_2TY_NoLED]
platform = intel_mcs51
board = STC8H1K08
board_build.f_cpu = 6000000L
extra_scripts = post:upload_stcgal.py
custom_stcgal_protocol = stc8g
custom_stcgal_trim = 6000
custom_stcgal_baud = 38400
build_flags =
    -Iinclude
    -Iboard/stc8h1k08_ir_lamp_remote
    -I../../../../foundation/Stc8hBase/core
    -I../../../../foundation/Stc8hBase/hal
    -I../../../../foundation/Stc8hBase/drivers
    -I../../../../foundation/Stc8hBase/utils
    -DSTC8H_TIMER0_ROLE_1T_DELAY
    -DAPP_IR_ACTIVE_LEVEL=0
    -DAPP_LED_FEEDBACK_ENABLE=0
