[env:STC8H1K08]
platform = intel_mcs51
board = STC8H1K08
board_build.f_cpu = 6000000L
extra_scripts = post:upload_stcgal.py
custom_stcgal_protocol = stc8g
custom_stcgal_trim = 6000
custom_stcgal_baud = 38400
build_flags =
    -Iinclude
    -Iboard/stc8h1k08_ir_lamp_remote
    -I../../../Stc8hBase/core
    -I../../../Stc8hBase/hal
    -I../../../Stc8hBase/drivers
    -I../../../Stc8hBase/utils
